# Generated by Django 5.1.3 on 2024-11-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('photos', models.CharField(max_length=3000000000000)),
                ('a_approval', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('comment', models.CharField(max_length=123456789012345678901234567890)),
                ('hate', models.IntegerField()),
            ],
        ),
    ]
