# Generated by Django 5.1.3 on 2024-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0014_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hate',
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
