# Generated by Django 5.1.3 on 2024-12-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0019_alter_post_photos_alter_udetails_an_lds_ym'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='toname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
