# Generated by Django 5.1.3 on 2024-11-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0002_faq_scriptures_alter_post_comment_alter_post_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='file',
            field=models.FileField(upload_to='static/'),
        ),
    ]
