# Generated by Django 5.1.3 on 2024-11-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0004_alter_faq_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='file',
            field=models.FileField(max_length=500, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scriptures',
            name='file',
            field=models.FileField(max_length=500, upload_to=None),
        ),
    ]
