# Generated by Django 5.1.3 on 2024-11-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0005_alter_faq_file_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
