# Generated by Django 5.1.3 on 2024-11-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0008_alter_faq_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='file',
            field=models.FileField(max_length=500, upload_to='document/'),
        ),
    ]
