# Generated by Django 5.1.3 on 2024-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0009_news_alter_faq_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='file',
            field=models.FileField(max_length=500, upload_to='media/'),
        ),
    ]
