# Generated by Django 5.1.3 on 2024-11-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
