# Generated by Django 5.1.3 on 2024-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0015_delete_hate_alter_comments_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('hate', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
