# Generated by Django 5.1.3 on 2024-12-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youngmen', '0017_alter_faq_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.FileField(max_length=500, upload_to='')),
                ('des', models.TextField()),
                ('tags', models.CharField(max_length=500)),
                ('an_lds_ym', models.BooleanField()),
            ],
        ),
    ]
